branch-defaults:
  main:
    environment: Formation-5-env
environment-defaults:
  Formation-1-env:
    branch: null
    repository: null
global:
  application_name: formation-5
  default_ec2_keyname: null
  default_platform: Go 1 running on 64bit Amazon Linux 2
  default_region: eu-west-3
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  sc: git
  workspace_type: Application
